# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_transfer_pb2 as grpc__transfer__pb2


class DataTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.grpcDataRemote = channel.unary_unary(
                '/DataTransfer/grpcDataRemote',
                request_serializer=grpc__transfer__pb2.RequestData.SerializeToString,
                response_deserializer=grpc__transfer__pb2.ResponseData.FromString,
                )
        self.grpcDataGet = channel.unary_unary(
                '/DataTransfer/grpcDataGet',
                request_serializer=grpc__transfer__pb2.RequestData.SerializeToString,
                response_deserializer=grpc__transfer__pb2.ResponseData.FromString,
                )


class DataTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def grpcDataRemote(self, request, context):
        """进阶Demo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def grpcDataGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'grpcDataRemote': grpc.unary_unary_rpc_method_handler(
                    servicer.grpcDataRemote,
                    request_deserializer=grpc__transfer__pb2.RequestData.FromString,
                    response_serializer=grpc__transfer__pb2.ResponseData.SerializeToString,
            ),
            'grpcDataGet': grpc.unary_unary_rpc_method_handler(
                    servicer.grpcDataGet,
                    request_deserializer=grpc__transfer__pb2.RequestData.FromString,
                    response_serializer=grpc__transfer__pb2.ResponseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def grpcDataRemote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataTransfer/grpcDataRemote',
            grpc__transfer__pb2.RequestData.SerializeToString,
            grpc__transfer__pb2.ResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def grpcDataGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataTransfer/grpcDataGet',
            grpc__transfer__pb2.RequestData.SerializeToString,
            grpc__transfer__pb2.ResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
