# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\nhelloworld\"\xb5\x01\n\x12GetDeptUserRequest\x12\x0f\n\x07\x64\x65pt_id\x18\x01 \x01(\r\x12\x11\n\tdept_name\x18\x02 \x01(\t\x12\x10\n\x08uid_list\x18\x03 \x03(\r\x12:\n\x06\x66ilter\x18\x04 \x03(\x0b\x32*.helloworld.GetDeptUserRequest.FilterEntry\x1a-\n\x0b\x46ilterEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc6\x01\n\x13GetDeptUserResponse\x12(\n\tuser_list\x18\x01 \x03(\x0b\x32\x15.helloworld.BasicUser\x12>\n\x08user_map\x18\x02 \x03(\x0b\x32,.helloworld.GetDeptUserResponse.UserMapEntry\x1a\x45\n\x0cUserMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.helloworld.BasicUser:\x02\x38\x01\"%\n\tBasicUser\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t2[\n\x07Greeter\x12P\n\x0bGetDeptUser\x12\x1e.helloworld.GetDeptUserRequest\x1a\x1f.helloworld.GetDeptUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDEPTUSERREQUEST_FILTERENTRY']._loaded_options = None
  _globals['_GETDEPTUSERREQUEST_FILTERENTRY']._serialized_options = b'8\001'
  _globals['_GETDEPTUSERRESPONSE_USERMAPENTRY']._loaded_options = None
  _globals['_GETDEPTUSERRESPONSE_USERMAPENTRY']._serialized_options = b'8\001'
  _globals['_GETDEPTUSERREQUEST']._serialized_start=27
  _globals['_GETDEPTUSERREQUEST']._serialized_end=208
  _globals['_GETDEPTUSERREQUEST_FILTERENTRY']._serialized_start=163
  _globals['_GETDEPTUSERREQUEST_FILTERENTRY']._serialized_end=208
  _globals['_GETDEPTUSERRESPONSE']._serialized_start=211
  _globals['_GETDEPTUSERRESPONSE']._serialized_end=409
  _globals['_GETDEPTUSERRESPONSE_USERMAPENTRY']._serialized_start=340
  _globals['_GETDEPTUSERRESPONSE_USERMAPENTRY']._serialized_end=409
  _globals['_BASICUSER']._serialized_start=411
  _globals['_BASICUSER']._serialized_end=448
  _globals['_GREETER']._serialized_start=450
  _globals['_GREETER']._serialized_end=541
# @@protoc_insertion_point(module_scope)
