# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transfer.grpc_mode.test.pb.msg2_pb2 as msg2__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeptUser = channel.unary_unary(
                '/helloworld.Greeter/GetDeptUser',
                request_serializer=msg2__pb2.GetDeptUserRequest.SerializeToString,
                response_deserializer=msg2__pb2.GetDeptUserResponse.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDeptUser(self, request, context):
        """进阶Demo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeptUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeptUser,
                    request_deserializer=msg2__pb2.GetDeptUserRequest.FromString,
                    response_serializer=msg2__pb2.GetDeptUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDeptUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Greeter/GetDeptUser',
            msg2__pb2.GetDeptUserRequest.SerializeToString,
            msg2__pb2.GetDeptUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
